apiVersion: v1
kind: ConfigMap
metadata:
  name: simpson-stg-turn-config
  namespace: simpson-videochat
data:
  turn_config: |
    listening-port=3478
    verbose
    lt-cred-mech
    user=simpson:simpson5aver
    realm=simpson-turns.tgl-cloud.com
    mongo-userdb="mongodb://simpson-stg-mongo-turn-service.simpson-videochat.svc.cluster.local:27017/coturn"
